name: CIDER-CI/cider-ci/ui/database
windows:
  2:
    name: migrate
    command: |
      # ./bin/rake db:migrate
  5:
    name: psql
    command: |
      psql -d cider-ci
  6:
    name: database
    post_command_send_keys: |
      cd database
      export RAILS_ENV=test
      bin/rails db:environment:set RAILS_ENV=test
      # bundle exec rake db:pg:terminate_connections
      # bundle exec rake db:drop db:create db:migrate
  7:
    name: test
    post_command_send_keys: |
      export RAILS_ENV=test
